# Generated by Django 3.2 on 2022-01-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210905_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('investor', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('startup', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('startup_name', models.CharField(max_length=30)),
                ('vision', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='BloggerAccount',
        ),
        migrations.DeleteModel(
            name='VendorAccount',
        ),
    ]
