# Generated by Django 3.2 on 2022-02-26 15:32

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220122_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='as_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='batch_of',
            field=models.CharField(default=2023, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='cur_stage',
            field=models.CharField(default='2023', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_uplaod_startup),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='num_founders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='to_seek_help',
            field=models.BooleanField(default=False),
        ),
    ]
